# Generated by Django 5.1.6 on 2025-03-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='titleee',
            new_name='title',
        ),
    ]
