# Generated by Django 5.1.6 on 2025-03-13 04:58

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_titleee_department_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=50, validators=[app.models.validate_department_title]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.FileField(upload_to='files/', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, validators=[app.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50, validators=[app.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=50, validators=[app.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanishi va 9 ta raqam bo‘lishi kerak!', regex='^\\+998[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(max_length=50, validators=[app.models.validate_region_title]),
        ),
    ]
